# Generated by Django 5.1.2 on 2024-10-25 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('account_number', models.CharField(default='36630705627409353701', max_length=20, verbose_name='Номер счета')),
                ('currency', models.CharField(choices=[('RUB', 'Российский Рубль'), ('USD', 'Доллар США')], max_length=3, verbose_name='Валюта счета')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sum', models.FloatField(blank=True, null=True, verbose_name='Сумма транзации')),
                ('from_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_acc_transaction', to='api.paymentaccountmodel')),
                ('to_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_acc_transaction', to='api.paymentaccountmodel')),
            ],
        ),
    ]
